[[headers]]
for = '/**'
[headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = """\
        default-src 'self'; \
        script-src 'self' 'unsafe-inline' \
            https://utteranc.es/client.js https://*.google-analytics.com https://*.googletagmanager.com http://www.instagram.com http://blog-dimlab-fr.disqus.com/embed.js https://c.disquscdn.com https://launchpad-wrapper.privacymanager.io https://launchpad.privacymanager.io; \
        style-src 'self' 'unsafe-inline' https://utteranc.es https://fonts.googleapis.com https://www.youtube.com http://www.instagram.com/embed.js https://c.disquscdn.com; \
        object-src 'none'; \
        base-uri 'self'; \
        connect-src 'self'
            https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com https://links.services.disqus.com https://geo.privacymanager.io/; \
        font-src 'self' https://fonts.gstatic.com; \
        frame-src 'self' https://utteranc.es https://www.youtube-nocookie.com https://www.youtube.com https://www.instagram.com https://disqus.com; \
        img-src 'self' data: https://i.vimeocdn.com https://i.ytimg.com https://*.google-analytics.com https://*.googletagmanager.com https://tile.openstreetmap.org https://referrer.disqus.com https://c.disquscdn.com http://cdn.viglink.com; \
        manifest-src 'self'; \
        media-src 'self' \
        """
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin"
    Permissions-Policy = """\
        geolocation=(), \
        midi=(), \
        sync-xhr=(), \
        microphone=(), \
        camera=(), \
        magnetometer=(), \
        gyroscope=(), \
        fullscreen=(), \
        payment=() \
        """
    cache-control = """\
        max-age=0, \
        no-cache, \
        no-store, \
        must-revalidate \
        """
    Access-Control-Allow-Origin = "*"
