[build]
    publish = "public"
    functions = "functions"

[build.environment]
    NODE_VERSION = "18.16.1"
    NPM_VERSION = "9.5.1"

[context.production]
    command = "npm run build"

[context.production.environment]
    HUGO_VERSION = "0.110.0"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[[headers]]
    for = "/*"
    [headers.values]
        Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
        X-Content-Type-Options = "nosniff"
        X-XSS-Protection = "1; mode=block"
        Content-Security-Policy = """\
            default-src 'self'; \
            child-src 'self' app.netlify.com; \
            script-src 'self' 'unsafe-inline' 'unsafe-eval' \
                https://*.netlify.app app.netlify.com netlify-cdp-loader.netlify.app \
                https://utteranc.es/client.js https://*.google-analytics.com https://*.googletagmanager.com http://www.instagram.com http://blog-dimlab-fr.disqus.com/embed.js https://c.disquscdn.com https://launchpad-wrapper.privacymanager.io https://launchpad.privacymanager.io https://unpkg.com https://identity.netlify.com; \
            style-src 'self' 'unsafe-inline' \
                https://*.netlify.app https://utteranc.es https://fonts.googleapis.com https://www.youtube.com https://c.disquscdn.com; \
            object-src 'none'; \
            base-uri 'self'; \
            connect-src 'self' webpack: \
                https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com https://links.services.disqus.com https://geo.privacymanager.io; \
            font-src 'self' https://*.netlify.app https://fonts.gstatic.com; \
            frame-src 'self' https://utteranc.es https://www.youtube-nocookie.com https://www.youtube.com https://www.instagram.com https://disqus.com \
                app.netlify.com; \
            img-src 'self' data: about: https://*.netlify.app https://i.vimeocdn.com https://i.ytimg.com https://*.google-analytics.com https://*.googletagmanager.com https://tile.openstreetmap.org https://referrer.disqus.com https://c.disquscdn.com http://cdn.viglink.com https://blog.dimlab.fr; \
            manifest-src 'self'; \
            media-src 'self' \
            """
        X-Frame-Options = "SAMEORIGIN"
        Referrer-Policy = "strict-origin"
        Permissions-Policy = """\
            geolocation=(), \
            midi=(), \
            sync-xhr=(), \
            microphone=(), \
            camera=(), \
            magnetometer=(), \
            gyroscope=(), \
            fullscreen=(), \
            payment=() \
            """
        cache-control = """\
            max-age=0, \
            no-cache, \
            no-store, \
            must-revalidate \
            """
        Access-Control-Allow-Origin = "*"

[context.deploy-preview]
    command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
    command = "npm run build -- -b $DEPLOY_PRIME_URL"

[context.next]
    command = "npm run build"

[context.next.environment]
    HUGO_ENV = "next"

[dev]
    framework = "#custom"
    command = "npm run start"
    targetPort = 1313
    port = 8888
    publish = "public"
    autoLaunch = false