backend:
  name: git-gateway
  branch: main
media_folder: "assets/images"
public_folder: "images"

collections:
  - name: "philippines" # Used in routes, e.g., /admin/collections/blog
    label: "philippines" # Used in the UI
    folder: "destinations/philippines" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}