[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Destinations"
  pageRef = "/destinations"
  weight = 20

[[main]]
  name = "Indonésie"
  pageRef = "/destinations/indonesie"
  parent = "Destinations"
  weight = 2

[[main]]
  name = "Singapour"
  pageRef = "/destinations/singapour"
  parent = "Destinations"
  weight = 3

[[main]]
  name = "Philippines"
  pageRef = "/destinations/philippines"
  parent = "Destinations"
  weight = 4

[[main]]
  name = "Vietnam"
  pageRef = "/destinations/vietnam"
  parent = "Destinations"
  weight = 5

[[main]]
  name = "Préparatifs"
  pageRef = "#"
  weight = 20

[[main]]
  name = "Budget"
  pageRef = "/preparatifs/budget"
  parent = "Préparatifs"
  weight = 2
[[main]]
  name = "Itinéraire"
  pageRef = "/preparatifs/itineraire"
  parent = "Préparatifs"
  weight = 1

[[social]]
  name = "Instagram"
  pre = "fab instagram"
  url = "https://www.instagram.com/dimitripuyet/"
  weight = 10

[[social]]
  name = "Polarsteps"
  pre = "fa compass"
  url = "https://www.polarsteps.com/EmmaPR7/9073467-tdm?s=ed63dfb1-b39f-4cf0-9412-5605ca604659"
  weight = 20

[[social]]
  name = "Youtube"
  pre = "fab youtube"
  url = "https://www.youtube.com/channel/UCe7dOEb9gO-jUI57VjiIJlA"
  weight = 30

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 10

[[sample]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 20

[[sample]]
  name = "Sample project"
  pageRef = "/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Another project"
  pageRef = "/projects/another-project/"
  parent = "Projects"
  weight = 2
# toml-docs-end sample-navigation